services:
  server:
    build: .
    ports:
      - 8007:5000
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=dummypassword
